"""Default catalogue used to seed Redis the first time the store boots."""

SEED_PRODUCTS = [
    {
        "id": "bandi-hyal",
        "brand": "BANDI Professional",
        "name": "Moisturising Concentrate with Hyaluronic Acid",
        "price_pence": 1300,
        "category": "skincare",
        "tag": "Bestseller",
        "image": "/assets/images/products/bandi-hyal.webp",
        "description": "An oil-free concentrate designed to layer effortlessly into a daily hydration ritual.",
        "source": "https://bandi-cosmetics.co.uk/collections/bestsellers/products/moisturizing-concentrate-with-hyaluronic-acid",
    },
    {
        "id": "bandi-butter",
        "brand": "BANDI Professional",
        "name": "Emollient Cleansing Butter 2-in-1",
        "price_pence": 1200,
        "category": "skincare",
        "tag": "New",
        "image": "/assets/images/products/bandi-butter.webp",
        "description": "A rich cleansing butter for removing make-up and leaving skin soft and comfortable.",
        "source": "https://bandi-cosmetics.co.uk/collections/bestsellers/products/emollient-cleansing-butter-2-in-1-make-up-remover-and-facial-cleanser",
    },
    {
        "id": "bandi-emulsion",
        "brand": "BANDI Professional",
        "name": "Deeply Moisturising Emulsion",
        "price_pence": 1750,
        "category": "skincare",
        "tag": "",
        "image": "/assets/images/products/bandi-emulsion.webp",
        "description": "A soft daily emulsion for dry, dehydrated and comfort-seeking skin.",
        "source": "https://bandi-cosmetics.co.uk/collections/bestsellers/products/deeply-moisturising-emulsion",
    },
    {
        "id": "bandi-peptide",
        "brand": "BANDI Professional",
        "name": "Rejuvenating Peptide Cream",
        "price_pence": 2700,
        "category": "skincare",
        "tag": "",
        "image": "/assets/images/products/bandi-peptide.webp",
        "description": "A peptide-rich face, neck and decolletage cream for a polished evening routine.",
        "source": "https://bandi-cosmetics.co.uk/collections/bestsellers/products/rejuvenating-peptide-cream-for-face-neck-and-decolletage",
    },
    {
        "id": "bandi-spf",
        "brand": "BANDI Professional",
        "name": "pre-D3 Advanced Moisturising Cream SPF 50",
        "price_pence": 2100,
        "category": "skincare",
        "tag": "",
        "image": "/assets/images/products/bandi-spf.webp",
        "description": "High daily protection paired with a moisturising, elegant cream texture.",
        "source": "https://bandi-cosmetics.co.uk/collections/bestsellers/products/pre-d3-advanced-moisturising-cream-spf-50",
    },
    {
        "id": "now-collagen",
        "brand": "NOW Foods",
        "name": "Collagen Peptides Powder, 227 g",
        "price_pence": 1895,
        "category": "wellness",
        "tag": "Beauty ritual",
        "image": "https://cloudinary.images-iherb.com/image/upload/f_auto%2Cq_auto%3Aeco/images/now/now03086/l/49.jpg",
        "description": "Unflavoured hydrolysed collagen peptides for a simple daily wellness routine.",
        "source": "https://www.iherb.com/pr/now-foods-collagen-peptides-powder-8-oz-227-g/86319",
    },
    {
        "id": "now-hyaluronic",
        "brand": "NOW Foods",
        "name": "Hyaluronic Acid with MSM, 60 Veg Capsules",
        "price_pence": 1595,
        "category": "wellness",
        "tag": "",
        "image": "https://cloudinary.images-iherb.com/image/upload/f_auto%2Cq_auto%3Aeco/images/now/now03156/l/61.jpg",
        "description": "Hyaluronic acid paired with MSM in an easy capsule format.",
        "source": "https://www.iherb.com/pr/now-foods-hyaluronic-acid-with-msm-60-veg-capsules/641",
    },
    {
        "id": "now-biotin",
        "brand": "NOW Foods",
        "name": "Biotin 5,000 mcg, 60 Veg Capsules",
        "price_pence": 895,
        "category": "wellness",
        "tag": "",
        "image": "https://cloudinary.images-iherb.com/image/upload/f_auto%2Cq_auto%3Aeco/images/now/now00471/l/62.jpg",
        "description": "A straightforward biotin supplement in vegetable capsules.",
        "source": "https://www.iherb.com/pr/now-foods-biotin-5-000-mcg-60-veg-capsules/447",
    },
    {
        "id": "now-d3k2",
        "brand": "NOW Foods",
        "name": "Vitamin D3 & K2, 120 Capsules",
        "price_pence": 1195,
        "category": "wellness",
        "tag": "",
        "image": "https://cloudinary.images-iherb.com/image/upload/f_auto%2Cq_auto%3Aeco/images/now/now00369/l/132.jpg",
        "description": "A combined D3 and K2 formula for everyday supplementation.",
        "source": "https://www.iherb.com/pr/now-foods-vitamin-d3-k2-120-capsules/10056",
    },
    {
        "id": "now-c1000",
        "brand": "NOW Foods",
        "name": "C-1000, 60 Tablets",
        "price_pence": 995,
        "category": "wellness",
        "tag": "",
        "image": "https://cloudinary.images-iherb.com/image/upload/f_auto%2Cq_auto%3Aeco/images/now/now00679/l/8.jpg",
        "description": "A high-strength vitamin C tablet for a simple daily routine.",
        "source": "https://www.iherb.com/pr/now-foods-c-1000-60-tablets/156873",
    },
    {
        "id": "now-omega",
        "brand": "NOW Foods",
        "name": "Omega-3 Fish Oil 1,000 mg, 100 Softgels",
        "price_pence": 1095,
        "category": "wellness",
        "tag": "",
        "image": "https://cloudinary.images-iherb.com/image/upload/f_auto%2Cq_auto%3Aeco/images/now/now01650/l/38.jpg",
        "description": "Molecularly distilled fish oil softgels containing EPA and DHA.",
        "source": "https://www.iherb.com/pr/now-foods-omega-3-fish-oil-1-000-mg-180-epa-120-dha-100-softgels/102333",
    },
    {
        "id": "now-czd",
        "brand": "NOW Foods",
        "name": "C-1000 Zinc & D-3, 100 Veg Capsules",
        "price_pence": 1695,
        "category": "wellness",
        "tag": "",
        "image": "https://cloudinary.images-iherb.com/image/upload/f_auto%2Cq_auto%3Aeco/images/now/now00696/l/39.jpg",
        "description": "Vitamin C, zinc and vitamin D3 together in one capsule formula.",
        "source": "https://www.iherb.com/pr/now-foods-c-1000-zinc-d-3-100-veg-capsules/117483",
    },
    {
        "id": "now-folic",
        "brand": "NOW Foods",
        "name": "Folic Acid with Vitamin B-12, 250 Tablets",
        "price_pence": 895,
        "category": "wellness",
        "tag": "",
        "image": "https://cloudinary.images-iherb.com/image/upload/f_auto%2Cq_auto%3Aeco/images/now/now00476/l/77.jpg",
        "description": "Folic acid with vitamin B-12 in a compact daily tablet.",
        "source": "https://www.iherb.com/pr/now-foods-folic-acid-250-tablets/601",
    },
]
